### ISSUE TITLE
Same as FroG?

### ISSUE THREAD

**Issue by tyeeman** [RadAd/RadGui#1]
I see this seems the same as FroG, the front end generator from Daniel Grob, yes? That would be cool. I see his website is gone! I've used FroG for many years and I was always wanting one feature removed, don't erase the file list after encoding. Would this be possible with your version here? How is it different from the original FroG??

**Comment by RadAd** [comment]
Hi,
Yes it was originally inspired by FroG. My version did at one time support
FroG config files but Im not sure if it still works.
Im not sure what you are referring to with erasing a file list.
Im don't quite remember the differences to frog. I just had some ideas for
improvements and it to be more generic.

**Comment by tyeeman** [comment]
Re: erasing file list, when you add files for processing, then run it, at the end of processing all your files are not in the list anymore (Batchlist>show). So you have to drag and drop all the same files again (or use the Add Files command). I do short encodes to test settings so I want all files to be encoded to remain until I manually delete them all.

**Comment by RadAd** [comment]
I haven't implemented the batch list functionality at all. It wasn't a feature I wanted.
